[workspace]
name = "diffmeshopt"
version = "0.1.0"
description = "Differentiable surface mesh generation for 3D segmentation refinement"
authors = ["saugat <saugat.kandel@u.northwestern.edu>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
generate-data = "python diffmeshopt/opt2d/generate_2d_data.py"
pytest = "pytest tests/opt2d"

[dependencies]
python = "3.12.*"

[pypi-options]
no-build-isolation = ["pytorch3d"]

[pypi-dependencies]
pytest = "*"
torch = ">=2.9.1, <3"
numpy = ">=2.4.0, <3"
trimesh = ">=4.10.1, <5"
matplotlib = ">=3.10.8, <4"
jupyterlab = ">=4.5.1, <5"
scikit-image = ">=0.26.0, <0.27"
tqdm = ">=4.67.1, <5"
torchvision = ">=0.24.1, <0.25"
ipywidgets = ">=8.1.8, <9"
jupyter = ">=1.1.1, <2"
zarr = ">=3.1.5, <4"
ome-zarr = ">=0.12.2, <0.13"
awscli = ">=1.44.13, <2"
cryoet-data-portal = ">=4.5.0, <5"
opencv-python = ">=4.11.0.86, <5"
plotly = ">=6.5.1, <7"
scipy = ">=1.17.0, <2"
ipykernel = ">=7.1.0, <8"
joblib = ">=1.5.3, <2"
click = ">=8.3.1, <9"
pydantic = ">=2.12.5, <3"
diffmeshopt = { path = ".", editable = true }

# --- Optional Dependencies ---

[feature.pytorch3d.pypi-dependencies]
pytorch3d = { git = "https://github.com/facebookresearch/pytorch3d.git" }

[environments]
# The default environment will NOT include pytorch3d
default = []
# The 'full' environment will include all base dependencies plus pytorch3d
full = ["pytorch3d"]
