[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "diffmeshopt"
version = "0.1.0"
description = "Differentiable surface mesh generation for 3D segmentation refinement"
authors = [{ name = "saugat", email = "saugat.kandel@u.northwestern.edu" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

# There is redundancy between [dependencies] and pixi.toml's [pypi-dependencies],
# but this is necessary because pyproject.toml is the standard way to specify
# dependencies for Python projects, while pixi.toml is used for managing the
# development environment and tasks.
dependencies = [
    "torch",              # Core tensor library
    "torchvision",        # Computer vision models and transforms
    "numpy",              # Numerical operations
    "scipy",              # Scientific computing, used for splines
    "trimesh",            # Mesh loading and processing
    "scikit-image",       # Image processing algorithms
    "opencv-python",      # Image processing utilities
    "zarr",               # Chunked array storage
    "ome-zarr",           # Bio-imaging specific zarr format
    "tqdm",               # Progress bars
    "click",              # For creating command-line interfaces
    "pydantic",           # Data validation and settings management
    "cryoet-data-portal", # Data access from CryoET data portal
    "jupyterlab",         # Interactive notebooks
    "ipywidgets",         # Interactive widgets for Jupyter
]

[project.optional-dependencies]
test = ["pytest"]
notebook = ["jupyterlab", "ipywidgets", "ipykernel", "matplotlib", "plotly"]
pytorch3d = [
    "setuptools",
    "pytorch3d @ git+https://github.com/facebookresearch/pytorch3d.git", # 3D geometry
]
[tool.ruff]
line-length = 99
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]
ignore = ["F401"]

[tool.ruff.lint.isort]
known-first-party = ["diffmeshopt"]

[tool.hatch.build.targets.wheel]
packages = ["diffmeshopt"]

[tool.hatch.metadata]
# Allow direct references (e.g., git URLs) in project.dependencies
allow-direct-references = true
