[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "diffmeshopt"
version = "0.1.0"
description = "Differentiable surface mesh generation for 3D segmentation refinement"
authors = [{ name = "saugat", email = "saugat.kandel@u.northwestern.edu" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "torch",
    "pytorch3d",
    "numpy",
    "trimesh",
    "matplotlib",
    "jupyter",
    "notebook",
    "scikit-image",
    "tqdm",
    "pytest",
]

#[project.urls]
#"Homepage" = "https://github.com/pypa/sampleproject"
#"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"

[tool.ruff]
line-length = 99
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]
ignore = []

[tool.ruff.lint.isort]
known-first-party = ["src"]
