name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pytest:
    name: Run Pytest    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.9.4
      with:
        # This matches the [tool.pixi.environments] 'ci' key
          activate-environment: ci
          # Pixi uses your lockfile to ensure the exact same versions locally and in CI
          frozen: true
          cache: true

    - name: Run tests
      run: |
        pixi run -e ci pytest
